### PR TITLE
command line options (strings only) 

### PR DESCRIPTION
**Pull request by SebSept**
docCommand can use command line options.

String parameters only.
If no config file is found.
./yiic doc app ../output/ name="mon app"

### CODE REVIEW

**Comment by SebSept** [comment]
just to mention that, I needed the `name="myapp"` option.

Because not using the config file (very small project) and not having a /protected/main.php file (have /protected/main_localhost.php (so also modified /index.php) )

**Comment by waiting-for-dev** [comment]
Thanks a lot for your pull request.

Current code wouldn't work if an extension is being documented, because in that case `arg[2]` would be `<ext-directory-name>`. A conditional should be added to check if `args[0]` is `yii` or `app`. The help message showed should be modified too with the `<config>` argument.

Anyway I'm not sure if this should be added. I think it's a good idea to have the config file, that way the api generation can be repeated easily as many times as needed and it's more error-proof, even for small projects. Furthermore, the command line options already are a little bit complicated to add another option.

**Comment by SebSept** [comment]
you're right for all points.
I'll move that to another personnal branch ...

**Comment by waiting-for-dev** [comment]
Thanks @SebSept

**Pull request closed without merging**
